#!/bin/bash
gcc -E ​$CFILE​ -o c                                                                                   2,1 All
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
0-preprocessor[+] [unix] (02:59 01/01/1970)                                                                                        2,1 All
-- INSERT --

